"""The five channels. Each one gets its own agent team, brand skill and story history."""

CHANNELS = [
    {
        "slug": "curiousduo", "name": "CuriousDuo", "tagline": "Two friends. One surprising idea.",
        "niche": "Engaging two-friend conversations about surprising science, technology, culture and everyday curiosities.",
        "strategy_json": {
            "conversation": True, "ideation_route": "frontier", "voice_name": "Puck",
            "voice": "Alex (Puck) and Sam (Zephyr), warm energetic friends, relaxed intelligible turn-taking",
            "narrative": "Alternate questions, reactions and answers between Alex and Sam; an interesting surprising payoff, no generic welcome",
            "visual_style": "high-quality recording studio, two consistent adult friends with dynamic microphones, alternating closeups, two-shots and topic-specific illustrative cutaways",
            "audience": "general adult", "made_for_kids_default": False,
            "topic_seeds": ["unexpected mechanisms behind everyday experiences", "creative technology", "human perception"],
        },
    },
    {
        "slug": "talemorrow",
        "name": "TaleMorrow",
        "tagline": "Stories that stay with you",
        "niche": "Drama, life lessons and human stories with a meaningful ending.",
        "strategy_json": {
            "voice_name": "Sulafat",
            "voice": "warm, unhurried, emotionally honest narrator",
            "narrative": "short fiction with one turn and one earned final line",
            "visual_style": "cinematic photographic realism, soft natural light, shallow depth of field, muted warm grade",
            "audience": "general adult",
            "made_for_kids_default": False,
            "topic_seeds": [
                "a small kindness repaid decades later",
                "a letter that arrives at the wrong house",
                "the last shift of a night-bus driver",
                "two strangers who share an umbrella",
                "a father teaching his daughter to drive",
            ],
        },
    },
    {
        "slug": "nowsift",
        "name": "NowSift",
        "tagline": "What matters, without the noise",
        "niche": "News and current events explained quickly and clearly.",
        "strategy_json": {
            "voice_name": "Rasalgethi",
            "voice": "calm, neutral, brisk explainer",
            "narrative": "what happened, why it matters, what happens next",
            "visual_style": "clean editorial photography, documentary framing, cool neutral grade, no text overlays",
            "audience": "general adult",
            "made_for_kids_default": False,
            "evergreen_only": True,
            "topic_seeds": [
                "how a central bank rate decision reaches your grocery bill",
                "why shipping routes reroute and what it costs",
                "how undersea cables carry the internet",
                "what an election recount actually involves",
                "how food inflation is measured",
            ],
        },
    },
    {
        "slug": "curionerve",
        "name": "CurioNerve",
        "tagline": "Feed your curiosity",
        "niche": "Facts, science, psychology and human behaviour.",
        "strategy_json": {
            "voice_name": "Sadaltager",
            "voice": "bright, curious, quick-witted",
            "narrative": "surprising claim, the mechanism, the payoff",
            "visual_style": "high-contrast macro and lab photography, vivid teal and amber accents, crisp detail",
            "audience": "curious teens and adults",
            "made_for_kids_default": False,
            "topic_seeds": [
                "why your brain edits out your own blinks",
                "the reason cut onions make you cry",
                "how memory rewrites itself every recall",
                "why crowds fall into step on bridges",
                "the psychology of the last slice",
            ],
        },
    },
    {
        "slug": "lorehush",
        "name": "LoreHush",
        "tagline": "The past still has secrets",
        "niche": "History, mysteries and forgotten stories.",
        "strategy_json": {
            "voice_name": "Enceladus",
            "voice": "hushed, atmospheric, deliberate",
            "narrative": "the setting, the mystery, the evidence, the unresolved question",
            "visual_style": "candlelit period realism, heavy chiaroscuro, dust motes, desaturated amber and slate grade",
            "audience": "general adult",
            "made_for_kids_default": False,
            "topic_seeds": [
                "the library that burned twice",
                "a shipwreck found in a wheat field",
                "the coin that dated a forgotten king",
                "the village that moved overnight",
                "a map with one impossible island",
            ],
        },
    },
    {
        "slug": "neurascify",
        "name": "NeuraScify",
        "tagline": "Understand what comes next",
        "niche": "AI, technology, innovation and the near future.",
        "strategy_json": {
            "voice_name": "Iapetus",
            "voice": "confident, precise, forward-looking",
            "narrative": "where we are, what changed, what it unlocks",
            "visual_style": "sleek near-future photography, cool blue and violet rim light, clean industrial surfaces",
            "audience": "general adult",
            "made_for_kids_default": False,
            "topic_seeds": [
                "how a data centre actually cools itself",
                "what on-device models change about privacy",
                "why robots struggle with doorknobs",
                "the energy cost of one generated image",
                "how chips get smaller than a virus",
            ],
        },
    },
]

BY_SLUG = {channel["slug"]: channel for channel in CHANNELS}
